export enum ErrorCode {
  UserAlreadyExists,
  UserNotExists,
  WrongPassword,
  InvalidEmailFormat,
  AccountLocked,
  AccessDenied,
  TimeoutError,
  InvalidToken,
  DuplicateEntry,
  InvalidInput,
  ServerError,
  DatabaseError,
  NotFound,
  Unauthorized,
  ExpiredSession,
  InvalidRequest,
  PaymentRequired,
  InsufficientPermissions,
  NeedOtp,
  InvalidOTP,
  ToManyRequests,
  PasswordNeedIt,
  PasskeyNeedIt,
  Passwordless,
}

export enum AuthMethod {
  PASSWORD = "PASSWORD",
  TWO_FACTOR = "TWO_FACTOR",
  MULTI_FACTOR = "MULTI_FACTOR",
  OAUTH = "OAUTH",
  JWT = "JWT",
  OPENID_CONNECT = "OPENID_CONNECT",
  BIOMETRIC = "BIOMETRIC",
  PASSKEY = "PASSKEY",
  SINGLE_SIGN_ON = "SINGLE_SIGN_ON",
  PASSWORDLESS = "PASSWORDLESS",
  CERTIFICATE = "CERTIFICATE",
  TOTP = "TOTP",
}
